---

- hosts: all
  become: true
  tasks: 


  - name: install updates (Centos)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Centos"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:  


  - name: install apache and php for Ubuntu servers
    apt:
      name: 
        - apache2
        - libapache2-mod-php  
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: install apache and php for Centos servers
    apt:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Centos"

